name: Android Release CI

on:
  release:
    types:
      - published

jobs:
  apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: ${{ github.event.inputs.name }}

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build project
        run: bash ./upload_archives.sh
